baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediatype = "text/html"
isHTML = true

[reveal_hugo]
theme = "robot-lung"

[params.reveal_hugo]
theme = "solarized"
custom_js = "fontawesome-all.js"
